### PR TITLE
Add JS file, more README updates

### PR DESCRIPTION
**Pull request by ngurney**
Sorry @caiceA, thought of a couple more small things that might be good, take or leave what you'd like 😃

### CODE REVIEW

**Comment by caiceA** [comment]
@ngurney i am so thankful i am not very regular user of github but you cleaned up and i liked it alot big thanks !!

**Comment by ngurney** [comment]
No problem! I love this theme and I’m trying to get more comfortable on GH, so using your repo as means to do that 😂 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by caiceA** [comment]
@ngurney I already added CSS to latest JS 1-2 hours ago, and the JS you added contains for highlighting unread channel names so i am removing from Readme this point,  otherwise, it looks better than mine

**Comment by ngurney** [comment]
Sounds great! 👍🏼

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
