### PR TITLE
Windows Install

### PR DESCRIPTION
**Pull request by benjamhooper**
- I've added a windows install script as promised in my [issue](https://github.com/caiceA/slack-black-theme/issues/82) I created. 

- I've added install instructions for the script in readme.

- I hope you didn't mind me adding a contributors list to the readme.

### CODE REVIEW

**Comment by matt1981m** [comment]
I would recommend adding a message to the readme that if the user installs nodejs after they open powershell, they will need to exit out of powershell and open it again, or the user will continue to get messages about unknown command/applet... 

This is a freakin piece of art... I have it installed it on each of the machines I use (both 4.0.1).  I had it installed manually on 4.0.0 on just one, as that was my main system and didn't have nodejs installed on the other at the time.

**Comment by benjamhooper** [comment]
Updated script and readme to reflect @matt1981m recommendation.

**Comment by caiceA** [comment]
@benjamhooper i updated the Readme file please can you make changes to the new readme i will merge then 
Thanks for your effort

**Comment by benjamhooper** [comment]
@caiceA merge successful, thank you!

**Comment by JeanRessouche** [comment]
The script works just fine (v4.0.1), thanks!

**Comment by benjamhooper** [comment]
@caiceA updated the readme to reflect current base branch(master). Is there a chance you could merge this in?

**Pull request merged**
