### PR TITLE
Fix thread reply theme

### PR DESCRIPTION
**Pull request by Column01**
- Fix thread replies to look more in tune with normal message replies
img
img

One question, is it possible to change the text that says `Reply...` to the same as the one in a normal channel? I was unable to find the section to change that. I've allowed edits so if you could change it, that would be amazing.

**Note:** Some changes are made by the repository owner, but were not committed to the main repository (only updated on the server)

### CODE REVIEW

**Comment by Column01** [comment]
I understand you might be working on making the theme pull CSS from the repository, so I understand if this cannot be accepted as is, but the colors are all set properly (minus the reply text before typing of course).

**Comment by caiceA** [comment]
did you try restarting you Slack/computer? 
i fixed this a day ago this is what i see

screenshot 2019-02-24 at 11 17 49
screenshot 2019-02-24 at 11 17 41

**Comment by Column01** [comment]
I had that, but I wanted it to look more like the normal message bar

**Comment by Column01** [comment]
Resolved conflicts to preserve changes

**Comment by Column01** [comment]
Thanks for the recent update! Will close this now :)

**Pull request closed without merging**
